### ISSUE TITLE
Misattribution in the "Staff projects" guide.

### ISSUE THREAD

**Issue by raskasa** [lethain/staff-eng#21]
In the [_"Staff project required"_ section](
https://github.com/lethain/staff-eng/blob/cf34edf351ba466f0e302b238cbae2b2710722d7/src/markdown/guides/staff-projects.md#staff-project-required) of the _"Staff projects"_ guide, the quote attributed to Ritu Vincent's story:

> I definitely had a Staff Project… Important note: The promotion didn’t come until I had also served some meaningful time as tech lead and delivered a lot of value there. But this project was definitely the firestarter.

is from [Ras Kasa Willams' story](https://staffeng.com/stories/ras-kasa-williams).

**Comment by lethain** [comment]
Hi Kasa, thanks for the flag, the correct quote there is similar

> I definitely had a Staff Project. Back in the day, Dropbox was initially a consumer product that people downloaded and installed on their machines. When we launched Dropbox for Business there was a request for both your personal and work Dropbox accounts to work simultaneously, including being able to switch across them without needing to log out and log back in.

Not sure how I made this mix up, appreciate you pointing it out, and apologies for the mistake.
