### ISSUE TITLE
improve legibility of body font

### ISSUE THREAD

**Issue by zeke** [lethain/staff-eng#51]
Hi @lethain 👋🏼 

Thanks for compiling this resource! I just started digging into the site today and have already found some insightful bits.

I've noticed that my eyes are getting a little squinty looking at the page, both on my laptop (macOS) and my phone (Android).

One potentially quick way to improve this would be to bump the font-weight from [300 to 400](https://fonts.google.com/specimen/Roboto), but it might also be worth exploring using other fonts for the site's body content.

If you're interested in exploring this change, I'd be happy to open a PR to help on it.

---

## Current (300)

<img width="663" alt="Screen Shot 2021-03-08 at 1 14 34 PM" src="https://user-images.githubusercontent.com/2289/110383330-f731cc00-8010-11eb-8cd3-83bd4db4932e.png">

## Possible (400?)

<img width="686" alt="Screen Shot 2021-03-08 at 1 14 46 PM" src="https://user-images.githubusercontent.com/2289/110383337-fac55300-8010-11eb-9637-c633a76016b3.png">

**Comment by lethain** [comment]
Hi @zeke -- totally agree that looks better. I just pushed `font-weight: 400` to staffeng.com, if you have other suggestions glad to make them or glad to accept a PR!

**Comment by zeke** [comment]
Looks good! Thanks for the quick response. Closing. 🙏🏼
